/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.camposdistribuidora.GUI;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rafae
 */
public class DlgAereo extends javax.swing.JDialog {
    
    private String nomeBloco;
    private int numeroBloco;

    /**
     * Creates new form DlgAereo
     */
    public DlgAereo(boolean modal) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_BLC16 = new javax.swing.JButton();
        jButton_BLC17 = new javax.swing.JButton();
        jButton_BLC18 = new javax.swing.JButton();
        jButton_BLC19 = new javax.swing.JButton();
        jButton_BLC20 = new javax.swing.JButton();
        jButton_BLC21 = new javax.swing.JButton();
        jButton_BLC22 = new javax.swing.JButton();
        jButton_BLC23 = new javax.swing.JButton();
        jButton_BLC24 = new javax.swing.JButton();
        jButton_BLC25 = new javax.swing.JButton();
        jButton_BLC26 = new javax.swing.JButton();
        jButton_BLC27 = new javax.swing.JButton();
        jButton_BLC28 = new javax.swing.JButton();
        jButton_BLC29 = new javax.swing.JButton();
        jButton_BLC30 = new javax.swing.JButton();
        jButton_BLC31 = new javax.swing.JButton();
        jButton_BLC35 = new javax.swing.JButton();
        jButton_BLC32 = new javax.swing.JButton();
        jButton_BLC33 = new javax.swing.JButton();
        jButton_BLC34 = new javax.swing.JButton();
        jButton_BLC11 = new javax.swing.JButton();
        jButton_BLC12 = new javax.swing.JButton();
        jButton_BLC13 = new javax.swing.JButton();
        jButton_BLC14 = new javax.swing.JButton();
        jButton_BLC15 = new javax.swing.JButton();
        jButton_BLC01 = new javax.swing.JButton();
        jButton_BLC02 = new javax.swing.JButton();
        jButton_BLC03 = new javax.swing.JButton();
        jButton_BLC04 = new javax.swing.JButton();
        jButton_BLC05 = new javax.swing.JButton();
        jButton_BLC06 = new javax.swing.JButton();
        jButton_BLC07 = new javax.swing.JButton();
        jButton_BLC08 = new javax.swing.JButton();
        jButton_BLC09 = new javax.swing.JButton();
        jButton_BLC10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton_BLC36 = new javax.swing.JButton();
        jButton_BLC37 = new javax.swing.JButton();
        jButton_BLC38 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton7.setText("BLC 1");
        jButton7.setMaximumSize(new java.awt.Dimension(65, 15));
        jButton7.setMinimumSize(new java.awt.Dimension(65, 15));
        jButton7.setPreferredSize(new java.awt.Dimension(65, 15));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(216, 546));
        setMinimumSize(new java.awt.Dimension(216, 546));
        setModal(true);

        jLabel1.setText("CAIXAS");

        jButton_BLC16.setText("16");
        jButton_BLC16.setBorder(null);
        jButton_BLC16.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC16.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC16.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC17.setText("17");
        jButton_BLC17.setBorder(null);
        jButton_BLC17.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC17.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC17.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC18.setText("18");
        jButton_BLC18.setBorder(null);
        jButton_BLC18.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC18.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC18.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC19.setText("19");
        jButton_BLC19.setBorder(null);
        jButton_BLC19.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC19.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC19.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC20.setText("20");
        jButton_BLC20.setBorder(null);
        jButton_BLC20.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC20.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC20.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC21.setText("21");
        jButton_BLC21.setBorder(null);
        jButton_BLC21.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC21.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC21.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC22.setText("22");
        jButton_BLC22.setBorder(null);
        jButton_BLC22.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC22.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC22.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC23.setText("23");
        jButton_BLC23.setBorder(null);
        jButton_BLC23.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC23.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC23.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC24.setText("24");
        jButton_BLC24.setBorder(null);
        jButton_BLC24.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC24.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC24.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC25.setText("25");
        jButton_BLC25.setBorder(null);
        jButton_BLC25.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC25.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC25.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC26.setText("26");
        jButton_BLC26.setBorder(null);
        jButton_BLC26.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC26.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC26.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC27.setText("27");
        jButton_BLC27.setBorder(null);
        jButton_BLC27.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC27.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC27.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC28.setText("28");
        jButton_BLC28.setBorder(null);
        jButton_BLC28.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC28.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC28.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC29.setText("29");
        jButton_BLC29.setBorder(null);
        jButton_BLC29.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC29.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC29.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC30.setText("30");
        jButton_BLC30.setBorder(null);
        jButton_BLC30.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC30.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC30.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC31.setText("31");
        jButton_BLC31.setBorder(null);
        jButton_BLC31.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC31.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC31.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC35.setText("35");
        jButton_BLC35.setBorder(null);
        jButton_BLC35.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC35.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC35.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC32.setText("32");
        jButton_BLC32.setBorder(null);
        jButton_BLC32.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC32.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC32.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC33.setText("33");
        jButton_BLC33.setBorder(null);
        jButton_BLC33.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC33.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC33.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC34.setText("34");
        jButton_BLC34.setBorder(null);
        jButton_BLC34.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC34.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC34.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC11.setText("11");
        jButton_BLC11.setBorder(null);
        jButton_BLC11.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC11.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC11.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC12.setText("12");
        jButton_BLC12.setBorder(null);
        jButton_BLC12.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC12.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC12.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC13.setText("13");
        jButton_BLC13.setBorder(null);
        jButton_BLC13.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC13.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC13.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC14.setText("14");
        jButton_BLC14.setBorder(null);
        jButton_BLC14.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC14.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC14.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC15.setText("15");
        jButton_BLC15.setBorder(null);
        jButton_BLC15.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC15.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC15.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC01.setText("01");
        jButton_BLC01.setBorder(null);
        jButton_BLC01.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC01.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC01.setPreferredSize(new java.awt.Dimension(70, 15));
        jButton_BLC01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BLC01ActionPerformed(evt);
            }
        });

        jButton_BLC02.setText("02");
        jButton_BLC02.setBorder(null);
        jButton_BLC02.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC02.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC02.setPreferredSize(new java.awt.Dimension(70, 15));
        jButton_BLC02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BLC02ActionPerformed(evt);
            }
        });

        jButton_BLC03.setText("03");
        jButton_BLC03.setToolTipText("");
        jButton_BLC03.setBorder(null);
        jButton_BLC03.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC03.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC03.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC04.setText("04");
        jButton_BLC04.setBorder(null);
        jButton_BLC04.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC04.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC04.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC05.setText("05");
        jButton_BLC05.setBorder(null);
        jButton_BLC05.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC05.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC05.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC06.setText("06");
        jButton_BLC06.setBorder(null);
        jButton_BLC06.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC06.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC06.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC07.setText("07");
        jButton_BLC07.setBorder(null);
        jButton_BLC07.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC07.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC07.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC08.setText(" 08");
        jButton_BLC08.setBorder(null);
        jButton_BLC08.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC08.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC08.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC09.setText("09");
        jButton_BLC09.setBorder(null);
        jButton_BLC09.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC09.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC09.setPreferredSize(new java.awt.Dimension(70, 15));

        jButton_BLC10.setText("10");
        jButton_BLC10.setBorder(null);
        jButton_BLC10.setMaximumSize(new java.awt.Dimension(70, 15));
        jButton_BLC10.setMinimumSize(new java.awt.Dimension(70, 15));
        jButton_BLC10.setPreferredSize(new java.awt.Dimension(70, 15));

        jLabel2.setText("CORREDOR");

        jButton_BLC36.setText("36");
        jButton_BLC36.setBorder(null);
        jButton_BLC36.setMaximumSize(new java.awt.Dimension(15, 70));
        jButton_BLC36.setMinimumSize(new java.awt.Dimension(15, 70));
        jButton_BLC36.setPreferredSize(new java.awt.Dimension(15, 70));

        jButton_BLC37.setText("37");
        jButton_BLC37.setBorder(null);
        jButton_BLC37.setMaximumSize(new java.awt.Dimension(15, 70));
        jButton_BLC37.setMinimumSize(new java.awt.Dimension(15, 70));
        jButton_BLC37.setPreferredSize(new java.awt.Dimension(15, 70));

        jButton_BLC38.setText("38");
        jButton_BLC38.setBorder(null);
        jButton_BLC38.setMaximumSize(new java.awt.Dimension(15, 70));
        jButton_BLC38.setMinimumSize(new java.awt.Dimension(15, 70));
        jButton_BLC38.setPreferredSize(new java.awt.Dimension(15, 70));

        jLabel3.setText("FUNDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_BLC17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_BLC20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_BLC19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_BLC16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_BLC02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_BLC01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_BLC05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BLC04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_BLC36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_BLC36, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_BLC37, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_BLC38, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_BLC15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButton_BLC07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_BLC35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_BLC24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton_BLC17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jButton_BLC16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BLC01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BLC01ActionPerformed
        try {
            nomeBloco = "BLC01";
            numeroBloco = 0;
            DlgBloco tela4 = new DlgBloco(nomeBloco,numeroBloco,true);
            tela4.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DlgAereo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_BLC01ActionPerformed

    private void jButton_BLC02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BLC02ActionPerformed
        try {
            nomeBloco = "BLC02";
            numeroBloco = 6;
            DlgBloco tela4 = new DlgBloco(nomeBloco,numeroBloco,true);
            tela4.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DlgAereo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_BLC02ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_BLC01;
    private javax.swing.JButton jButton_BLC02;
    private javax.swing.JButton jButton_BLC03;
    private javax.swing.JButton jButton_BLC04;
    private javax.swing.JButton jButton_BLC05;
    private javax.swing.JButton jButton_BLC06;
    private javax.swing.JButton jButton_BLC07;
    private javax.swing.JButton jButton_BLC08;
    private javax.swing.JButton jButton_BLC09;
    private javax.swing.JButton jButton_BLC10;
    private javax.swing.JButton jButton_BLC11;
    private javax.swing.JButton jButton_BLC12;
    private javax.swing.JButton jButton_BLC13;
    private javax.swing.JButton jButton_BLC14;
    private javax.swing.JButton jButton_BLC15;
    private javax.swing.JButton jButton_BLC16;
    private javax.swing.JButton jButton_BLC17;
    private javax.swing.JButton jButton_BLC18;
    private javax.swing.JButton jButton_BLC19;
    private javax.swing.JButton jButton_BLC20;
    private javax.swing.JButton jButton_BLC21;
    private javax.swing.JButton jButton_BLC22;
    private javax.swing.JButton jButton_BLC23;
    private javax.swing.JButton jButton_BLC24;
    private javax.swing.JButton jButton_BLC25;
    private javax.swing.JButton jButton_BLC26;
    private javax.swing.JButton jButton_BLC27;
    private javax.swing.JButton jButton_BLC28;
    private javax.swing.JButton jButton_BLC29;
    private javax.swing.JButton jButton_BLC30;
    private javax.swing.JButton jButton_BLC31;
    private javax.swing.JButton jButton_BLC32;
    private javax.swing.JButton jButton_BLC33;
    private javax.swing.JButton jButton_BLC34;
    private javax.swing.JButton jButton_BLC35;
    private javax.swing.JButton jButton_BLC36;
    private javax.swing.JButton jButton_BLC37;
    private javax.swing.JButton jButton_BLC38;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
