/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.camposdistribuidora.GUI;

/**
 *
 * @author rafae
 */
public class DlgBloco extends javax.swing.JDialog {

    /**
     * Creates new form DlgBloco
     */
    public DlgBloco(String nomeBloco,int numeroBloco, boolean modal) {      
        initComponents();
        jLabel_NomeBloco.setText(nomeBloco);
        setNumEtq(numeroBloco);
    }
    
    public void setNumEtq(int numeroBloco){
        jLabel_PrimeiraEtqBloco.setText(String.valueOf(numeroBloco*1));
        jLabel_SegundaEtqBloco.setText(String.valueOf(numeroBloco*2));
        jLabel_TerceiraEtqBloco.setText(String.valueOf(numeroBloco*3));
        jLabel_QuartaEtqBloco.setText(String.valueOf(numeroBloco*4));
        jLabel_QuintaEtqBloco.setText(String.valueOf(numeroBloco*5));
        jLabel_SextaEtqBloco.setText(String.valueOf(numeroBloco*6));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_NomeBloco = new javax.swing.JLabel();
        jLabel_QuintaEtqBloco = new javax.swing.JLabel();
        jLabel_QuartaEtqBloco = new javax.swing.JLabel();
        jLabel_SegundaEtqBloco = new javax.swing.JLabel();
        jLabel_PrimeiraEtqBloco = new javax.swing.JLabel();
        jLabel_TerceiraEtqBloco = new javax.swing.JLabel();
        jLabel_SextaEtqBloco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(603, 473));
        setMinimumSize(new java.awt.Dimension(603, 473));

        jLabel_NomeBloco.setText("nome");

        jLabel_QuintaEtqBloco.setText("etq5");

        jLabel_QuartaEtqBloco.setText("etq4");

        jLabel_SegundaEtqBloco.setText("etq2");

        jLabel_PrimeiraEtqBloco.setText("etq1");

        jLabel_TerceiraEtqBloco.setText("etq3");

        jLabel_SextaEtqBloco.setText("etq6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_NomeBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_QuintaEtqBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_SextaEtqBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_TerceiraEtqBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_QuartaEtqBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_PrimeiraEtqBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_SegundaEtqBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_NomeBloco, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_QuintaEtqBloco)
                    .addComponent(jLabel_SextaEtqBloco))
                .addGap(116, 116, 116)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_QuartaEtqBloco)
                    .addComponent(jLabel_TerceiraEtqBloco))
                .addGap(116, 116, 116)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_PrimeiraEtqBloco)
                    .addComponent(jLabel_SegundaEtqBloco))
                .addGap(116, 116, 116))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_NomeBloco;
    private javax.swing.JLabel jLabel_PrimeiraEtqBloco;
    private javax.swing.JLabel jLabel_QuartaEtqBloco;
    private javax.swing.JLabel jLabel_QuintaEtqBloco;
    private javax.swing.JLabel jLabel_SegundaEtqBloco;
    private javax.swing.JLabel jLabel_SextaEtqBloco;
    private javax.swing.JLabel jLabel_TerceiraEtqBloco;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
