/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.camposdistribuidora.GUI;

import com.mycompany.camposdistribuidora.Cadastro;
import com.mycompany.camposdistribuidora.GerenciadorCadastros;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class DlgCadastro extends javax.swing.JDialog {

    private String matriculaSelecionada;
    private boolean editando;
    private GerenciadorCadastros gerente;

    public DlgCadastro(boolean modal) {
        this.editando = false;
        this.matriculaSelecionada = "";
        this.gerente = new GerenciadorCadastros();
        initComponents();
        setTitle("Cadastro");
        this.habilitarCampos(false);
        this.limparCampos();
        this.jTextArea_Cadastro_Saida.setEditable(false);
        try {
            gerente.carregarDoArquivo("ListagemCadastrosUsuarios.csv");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DlgCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea_Cadastro_Saida.setText(gerente.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Cadastro_Novo = new javax.swing.JButton();
        jButton_Cadastro_Editar = new javax.swing.JButton();
        jButton_Cadastro_Cancelar = new javax.swing.JButton();
        jButton_Cadastro_Excluir = new javax.swing.JButton();
        jButton_Cadastro_Salvar = new javax.swing.JButton();
        jLabel_Cadastro_Título = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_Cadastro_Nome = new javax.swing.JLabel();
        jLabel_Cadastro_CPF = new javax.swing.JLabel();
        jTextField_Cadastro_Nome = new javax.swing.JTextField();
        jTextField_Cadastro_CPF = new javax.swing.JTextField();
        jLabel_Cadastro_Matrícula = new javax.swing.JLabel();
        jLabel_Cadastro_Cargo = new javax.swing.JLabel();
        jTextField_Cadastro_Matricula = new javax.swing.JTextField();
        jTextField_Cadastro_Cargo = new javax.swing.JTextField();
        jLabel_Cadastro_Email = new javax.swing.JLabel();
        jLabel_Cadastro_Senha = new javax.swing.JLabel();
        jTextField_Cadastro_Email = new javax.swing.JTextField();
        jTextField_Cadastro_Senha = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Cadastro_Saida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jButton_Cadastro_Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-novo.png"))); // NOI18N
        jButton_Cadastro_Novo.setText("Novo");
        jButton_Cadastro_Novo.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Novo.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Novo.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastro_NovoActionPerformed(evt);
            }
        });

        jButton_Cadastro_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-editar-20.png"))); // NOI18N
        jButton_Cadastro_Editar.setText("Editar");
        jButton_Cadastro_Editar.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Editar.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Editar.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastro_EditarActionPerformed(evt);
            }
        });

        jButton_Cadastro_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancelar-20 (1).png"))); // NOI18N
        jButton_Cadastro_Cancelar.setText("Cancelar");
        jButton_Cadastro_Cancelar.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Cancelar.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Cancelar.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastro_CancelarActionPerformed(evt);
            }
        });

        jButton_Cadastro_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-excluir.png"))); // NOI18N
        jButton_Cadastro_Excluir.setText("Excluir");
        jButton_Cadastro_Excluir.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Excluir.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Excluir.setPreferredSize(new java.awt.Dimension(100, 27));
        jButton_Cadastro_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastro_ExcluirActionPerformed(evt);
            }
        });

        jButton_Cadastro_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-salvar.png"))); // NOI18N
        jButton_Cadastro_Salvar.setText("Salvar");
        jButton_Cadastro_Salvar.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Salvar.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Salvar.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_Cadastro_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastro_SalvarActionPerformed(evt);
            }
        });

        jLabel_Cadastro_Título.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabel_Cadastro_Título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cadastro_Título.setText("Cadastro de Usuários");

        jLabel_Cadastro_Nome.setText("Nome:");

        jLabel_Cadastro_CPF.setText("CPF:");

        jLabel_Cadastro_Matrícula.setText("Matrícula:");

        jLabel_Cadastro_Cargo.setText("Cargo:");

        jLabel_Cadastro_Email.setText("Email:");

        jLabel_Cadastro_Senha.setText("Senha:");

        jTextArea_Cadastro_Saida.setColumns(20);
        jTextArea_Cadastro_Saida.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Cadastro_Saida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Cadastro_Título, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Cadastro_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton_Cadastro_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton_Cadastro_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton_Cadastro_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Cadastro_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Cadastro_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Cadastro_CPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Cadastro_Nome)
                                    .addComponent(jTextField_Cadastro_CPF, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Cadastro_Matrícula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Cadastro_Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Cadastro_Matricula, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTextField_Cadastro_Cargo))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Cadastro_Senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Cadastro_Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Cadastro_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTextField_Cadastro_Senha))))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Cadastro_Título, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cadastro_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cadastro_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cadastro_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cadastro_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cadastro_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cadastro_Nome)
                    .addComponent(jTextField_Cadastro_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cadastro_Matrícula)
                    .addComponent(jTextField_Cadastro_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cadastro_Email)
                    .addComponent(jTextField_Cadastro_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Cadastro_CPF)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Cadastro_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Cadastro_Cargo)
                        .addComponent(jTextField_Cadastro_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Cadastro_Senha)
                        .addComponent(jTextField_Cadastro_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void limparCampos() {
        this.jTextField_Cadastro_Nome.setText("");
        this.jTextField_Cadastro_CPF.setText("");
        this.jTextField_Cadastro_Cargo.setText("");
        this.jTextField_Cadastro_Email.setText("");
        this.jTextField_Cadastro_Matricula.setText("");
        this.jTextField_Cadastro_Senha.setText("");
    }

    public void habilitarCampos(boolean flag) {
        this.jTextField_Cadastro_Nome.setEnabled(flag);
        this.jTextField_Cadastro_CPF.setEnabled(flag);
        this.jTextField_Cadastro_Cargo.setEnabled(flag);
        this.jTextField_Cadastro_Email.setEnabled(flag);
        this.jTextField_Cadastro_Matricula.setEnabled(flag);
        this.jTextField_Cadastro_Senha.setEnabled(flag);
    }

    public Cadastro camposParaObjeto() {
        Cadastro cadastro = new Cadastro();
        cadastro.setNome(jTextField_Cadastro_Nome.getText());
        cadastro.setCargo(jTextField_Cadastro_Cargo.getText());
        cadastro.setCpf(jTextField_Cadastro_CPF.getText());
        cadastro.setEmail(jTextField_Cadastro_Email.getText());
        cadastro.setMatricula(jTextField_Cadastro_Matricula.getText());
        cadastro.setSenha(jTextField_Cadastro_Senha.getText());
        return cadastro;
    }

    public void objetoParaCampos(Cadastro cadastro) {
        jTextField_Cadastro_Nome.setText(cadastro.getNome());
        jTextField_Cadastro_CPF.setText(cadastro.getCpf());
        jTextField_Cadastro_Cargo.setText(cadastro.getCargo());
        jTextField_Cadastro_Email.setText(cadastro.getEmail());
        jTextField_Cadastro_Matricula.setText(cadastro.getMatricula());
        jTextField_Cadastro_Senha.setText(cadastro.getSenha());
    }

    private void jButton_Cadastro_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastro_NovoActionPerformed
        this.limparCampos();
        this.habilitarCampos(true);
        this.editando = false;
    }//GEN-LAST:event_jButton_Cadastro_NovoActionPerformed

    private void jButton_Cadastro_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastro_EditarActionPerformed
        this.matriculaSelecionada = JOptionPane.showInputDialog("Informe a matrícula do usuário:", "");
        Cadastro cadastroEditando = this.gerente.buscarCadastro(matriculaSelecionada);
        if (cadastroEditando != null) {
            this.editando = true;
            this.limparCampos();
            this.habilitarCampos(true);
            objetoParaCampos(cadastroEditando);

        } else {
            System.out.println("cadastro inexistente");
            JOptionPane.showMessageDialog(this, "A matrícula informada não foi encontrada no sistema.", "Cadastro Inexistente", HEIGHT);
        }
    }//GEN-LAST:event_jButton_Cadastro_EditarActionPerformed

    private void jButton_Cadastro_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastro_CancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_jButton_Cadastro_CancelarActionPerformed

    private void jButton_Cadastro_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastro_ExcluirActionPerformed
        this.matriculaSelecionada = JOptionPane.showInputDialog("Informe a matrícula do usuário:", "");
        Cadastro cadastro = this.gerente.buscarCadastro(matriculaSelecionada);
        if (cadastro == null) {
            JOptionPane.showMessageDialog(this, "A matrícula informada não foi encontrada no sistema.", "Cadastro Inexistente", HEIGHT);
        } else {
            this.gerente.removerCadastro(matriculaSelecionada);
            JOptionPane.showMessageDialog(this, "Cadastro excluído com sucesso.", "Cadastro Excluído", HEIGHT);
        }
        String listagem = this.gerente.toString();
        jTextArea_Cadastro_Saida.setText(listagem);

    }//GEN-LAST:event_jButton_Cadastro_ExcluirActionPerformed

    private void jButton_Cadastro_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastro_SalvarActionPerformed
        Cadastro novoCadastro = this.camposParaObjeto();
        if (this.editando == true) {
            this.gerente.atualizarCadastro(this.matriculaSelecionada, novoCadastro);
        } else {
            this.gerente.adicionarCadastros(novoCadastro);

        }
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
        String listagem = gerente.toString();
        jTextArea_Cadastro_Saida.setText(listagem);
        try {
            gerente.salvarNoArquivo("ListagemCadastrosUsuarios.csv");
        } catch (IOException ex) {
            Logger.getLogger(DlgCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Cadastro_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cadastro_Cancelar;
    private javax.swing.JButton jButton_Cadastro_Editar;
    private javax.swing.JButton jButton_Cadastro_Excluir;
    private javax.swing.JButton jButton_Cadastro_Novo;
    private javax.swing.JButton jButton_Cadastro_Salvar;
    private javax.swing.JLabel jLabel_Cadastro_CPF;
    private javax.swing.JLabel jLabel_Cadastro_Cargo;
    private javax.swing.JLabel jLabel_Cadastro_Email;
    private javax.swing.JLabel jLabel_Cadastro_Matrícula;
    private javax.swing.JLabel jLabel_Cadastro_Nome;
    private javax.swing.JLabel jLabel_Cadastro_Senha;
    private javax.swing.JLabel jLabel_Cadastro_Título;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea_Cadastro_Saida;
    private javax.swing.JTextField jTextField_Cadastro_CPF;
    private javax.swing.JTextField jTextField_Cadastro_Cargo;
    private javax.swing.JTextField jTextField_Cadastro_Email;
    private javax.swing.JTextField jTextField_Cadastro_Matricula;
    private javax.swing.JTextField jTextField_Cadastro_Nome;
    private javax.swing.JTextField jTextField_Cadastro_Senha;
    // End of variables declaration//GEN-END:variables
}
