/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.camposdistribuidora.GUI;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rafae
 */
public class DlgMenu extends javax.swing.JDialog {

    /**
     * Creates new form DlgMenuu
     */
    public DlgMenu(boolean modal) {
        initComponents();
        setTitle("Menu");
        jButton_Relatorio.setEnabled(false);
        jButton_Vazio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Estoque = new javax.swing.JButton();
        jButton_Relatorio = new javax.swing.JButton();
        jButton_Aereo = new javax.swing.JButton();
        jButton_Vazio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(216, 216));
        setMinimumSize(new java.awt.Dimension(216, 216));
        setModal(true);

        jButton_Estoque.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-armazém-20.png"))); // NOI18N
        jButton_Estoque.setText("Estoque");
        jButton_Estoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Estoque.setMaximumSize(new java.awt.Dimension(90, 90));
        jButton_Estoque.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton_Estoque.setPreferredSize(new java.awt.Dimension(90, 90));
        jButton_Estoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EstoqueActionPerformed(evt);
            }
        });

        jButton_Relatorio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_Relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-relatório-20.png"))); // NOI18N
        jButton_Relatorio.setText("Relatório");
        jButton_Relatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Relatorio.setMaximumSize(new java.awt.Dimension(90, 90));
        jButton_Relatorio.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton_Relatorio.setPreferredSize(new java.awt.Dimension(90, 90));
        jButton_Relatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton_Aereo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_Aereo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-empilhadeira-20.png"))); // NOI18N
        jButton_Aereo.setText("Aéreo");
        jButton_Aereo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Aereo.setMaximumSize(new java.awt.Dimension(90, 90));
        jButton_Aereo.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton_Aereo.setPreferredSize(new java.awt.Dimension(90, 90));
        jButton_Aereo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Aereo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AereoActionPerformed(evt);
            }
        });

        jButton_Vazio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_Vazio.setText("???");
        jButton_Vazio.setMaximumSize(new java.awt.Dimension(90, 90));
        jButton_Vazio.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton_Vazio.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Aereo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Vazio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Aereo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Vazio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EstoqueActionPerformed
        DlgCadastroProdutos cadastro = new DlgCadastroProdutos(true);
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton_EstoqueActionPerformed

    private void jButton_AereoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AereoActionPerformed
        try {
            DlgAereo tela3 = new DlgAereo(true);
            tela3.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DlgMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_AereoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Aereo;
    private javax.swing.JButton jButton_Estoque;
    private javax.swing.JButton jButton_Relatorio;
    private javax.swing.JButton jButton_Vazio;
    // End of variables declaration//GEN-END:variables
}
