/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.GerenciadorCadastros;
import factory.Persistencia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Administrador;
import model.DAO.CadastroSQLiteJPADAO;
import model.Funcionario;
import model.Operador;
import model.exception.CadastroException;

/**
 *
 * @author rafae
 */
public class DlgCadastroUsuario extends javax.swing.JDialog {

    private String cadastroSelecionado;
    private boolean editando;
    private GerenciadorCadastros gerente;

    public DlgCadastroUsuario(boolean modal) {
        super((java.awt.Frame) null, modal); // Certifique-se de passar o owner se necessário
        this.editando = false;
        this.cadastroSelecionado = "";
        this.gerente = new GerenciadorCadastros();
        initComponents();
        setTitle("Cadastro");
        this.habilitarCampos(false);
        this.limparCampos();
        jComboBox_CadastroUsuario_Cargo.setModel(new DefaultComboBoxModel<>(new String[]{"OPERADOR", "ADMINISTRADOR"}));
        // Inicialmente, desabilita o combo de ADM
        jComboBox_CadastroUsuario_Adm.setEnabled(false);
        // Adiciona listener para atualizar o combo de ADM de acordo com o cargo selecionado
        jComboBox_CadastroUsuario_Cargo.addActionListener(evt -> atualizarComboAdm());

        // Adiciona listener para fechar as conexões ao fechar a tela
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                // Fecha o EntityManagerFactory do JPA
                CadastroSQLiteJPADAO.closeEntityManagerFactory();
                // Fecha a conexão JDBC, se estiver aberta
                Persistencia.closeConnection();
            }
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Também pode ser chamado aqui, para garantir
                CadastroSQLiteJPADAO.closeEntityManagerFactory();
                Persistencia.closeConnection();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_CadastroUsuario_Novo = new javax.swing.JButton();
        jButton_CadastroUsuario_Editar = new javax.swing.JButton();
        jButton_CadastroUsuario_Cancelar = new javax.swing.JButton();
        jButton_CadastroUsuario_Excluir = new javax.swing.JButton();
        jButton_CadastroUsuario_Salvar = new javax.swing.JButton();
        jLabel_CadastroUsuario_Título = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_CadastroUsuario_Nome = new javax.swing.JLabel();
        jTextField_CadastroUsuario_Nome = new javax.swing.JTextField();
        jLabel_CadastroUsuario_CPF = new javax.swing.JLabel();
        jLabel_CadastroUsuario_Senha = new javax.swing.JLabel();
        jTextField_CadastroUsuario_CPF = new javax.swing.JTextField();
        jTextField_CadastroUsuario_Senha = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_CadastroUsuario_Matrícula = new javax.swing.JLabel();
        jTextField_CadastroUsuario_Matricula = new javax.swing.JTextField();
        jComboBox_CadastroUsuario_Adm = new javax.swing.JComboBox<>();
        jLabel_CadastroUsuario_Cargo = new javax.swing.JLabel();
        jLabel_CadastroUsuario_Email = new javax.swing.JLabel();
        jTextField_CadastroUsuario_Email = new javax.swing.JTextField();
        jLabel_CadastroUsuario_Adm = new javax.swing.JLabel();
        jComboBox_CadastroUsuario_Cargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(583, 145));
        setModal(true);
        setResizable(false);

        jButton_CadastroUsuario_Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-novo.png"))); // NOI18N
        jButton_CadastroUsuario_Novo.setText("Novo");
        jButton_CadastroUsuario_Novo.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Novo.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Novo.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_NovoActionPerformed(evt);
            }
        });

        jButton_CadastroUsuario_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-editar-20.png"))); // NOI18N
        jButton_CadastroUsuario_Editar.setText("Editar");
        jButton_CadastroUsuario_Editar.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Editar.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Editar.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_EditarActionPerformed(evt);
            }
        });

        jButton_CadastroUsuario_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancelar-20 (1).png"))); // NOI18N
        jButton_CadastroUsuario_Cancelar.setText("Cancelar");
        jButton_CadastroUsuario_Cancelar.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Cancelar.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Cancelar.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_CancelarActionPerformed(evt);
            }
        });

        jButton_CadastroUsuario_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-excluir.png"))); // NOI18N
        jButton_CadastroUsuario_Excluir.setText("Excluir");
        jButton_CadastroUsuario_Excluir.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Excluir.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Excluir.setPreferredSize(new java.awt.Dimension(100, 27));
        jButton_CadastroUsuario_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_ExcluirActionPerformed(evt);
            }
        });

        jButton_CadastroUsuario_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-salvar.png"))); // NOI18N
        jButton_CadastroUsuario_Salvar.setText("Salvar");
        jButton_CadastroUsuario_Salvar.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Salvar.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Salvar.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_SalvarActionPerformed(evt);
            }
        });

        jLabel_CadastroUsuario_Título.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_CadastroUsuario_Título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CadastroUsuario_Título.setText("Cadastro de Usuários");

        jLabel_CadastroUsuario_Nome.setText("Nome:");

        jTextField_CadastroUsuario_Nome.setMaximumSize(new java.awt.Dimension(210, 22));
        jTextField_CadastroUsuario_Nome.setMinimumSize(new java.awt.Dimension(210, 22));
        jTextField_CadastroUsuario_Nome.setPreferredSize(new java.awt.Dimension(210, 22));

        jLabel_CadastroUsuario_CPF.setText("CPF:");

        jLabel_CadastroUsuario_Senha.setText("Senha:");

        jTextField_CadastroUsuario_CPF.setMaximumSize(new java.awt.Dimension(190, 22));
        jTextField_CadastroUsuario_CPF.setMinimumSize(new java.awt.Dimension(190, 22));
        jTextField_CadastroUsuario_CPF.setPreferredSize(new java.awt.Dimension(190, 22));

        jTextField_CadastroUsuario_Senha.setMaximumSize(new java.awt.Dimension(190, 22));
        jTextField_CadastroUsuario_Senha.setMinimumSize(new java.awt.Dimension(190, 22));
        jTextField_CadastroUsuario_Senha.setPreferredSize(new java.awt.Dimension(190, 22));

        jLabel_CadastroUsuario_Matrícula.setText("Matricula:");

        jComboBox_CadastroUsuario_Adm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_CadastroUsuario_Cargo.setText("Cargo:");

        jLabel_CadastroUsuario_Email.setText("Email:");

        jLabel_CadastroUsuario_Adm.setText("ADM:");

        jComboBox_CadastroUsuario_Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CadastroUsuario_Título, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_CadastroUsuario_CPF)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_CadastroUsuario_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_CadastroUsuario_Email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CadastroUsuario_Email))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_CadastroUsuario_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CadastroUsuario_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_CadastroUsuario_Matrícula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CadastroUsuario_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel_CadastroUsuario_Senha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CadastroUsuario_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel_CadastroUsuario_Cargo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel_CadastroUsuario_Adm)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_CadastroUsuario_Cargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_CadastroUsuario_Adm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_CadastroUsuario_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton_CadastroUsuario_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton_CadastroUsuario_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton_CadastroUsuario_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_CadastroUsuario_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_CadastroUsuario_Título, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CadastroUsuario_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroUsuario_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroUsuario_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroUsuario_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroUsuario_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CadastroUsuario_Nome)
                    .addComponent(jTextField_CadastroUsuario_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CadastroUsuario_Senha)
                    .addComponent(jTextField_CadastroUsuario_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CadastroUsuario_Matrícula)
                    .addComponent(jTextField_CadastroUsuario_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CadastroUsuario_Cargo)
                    .addComponent(jComboBox_CadastroUsuario_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_CadastroUsuario_Adm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_CadastroUsuario_CPF)
                        .addComponent(jTextField_CadastroUsuario_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_CadastroUsuario_Email)
                        .addComponent(jTextField_CadastroUsuario_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_CadastroUsuario_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Método para limpar os campos, agora também limpando o email e resetando o combo de cargo
    public void limparCampos() {
        jTextField_CadastroUsuario_Nome.setText("");
        jTextField_CadastroUsuario_Senha.setText("");
        jTextField_CadastroUsuario_Matricula.setText("");
        jTextField_CadastroUsuario_CPF.setText("");
        jTextField_CadastroUsuario_Email.setText("");
        jComboBox_CadastroUsuario_Cargo.setSelectedIndex(0);
        jComboBox_CadastroUsuario_Adm.setSelectedItem(null);
    }

// Método para habilitar/desabilitar os campos, agora incluindo email e o combo box de cargo
    public void habilitarCampos(boolean flag) {
        jTextField_CadastroUsuario_Nome.setEnabled(flag);
        jTextField_CadastroUsuario_Senha.setEnabled(flag);
        jTextField_CadastroUsuario_Matricula.setEnabled(flag);
        jTextField_CadastroUsuario_CPF.setEnabled(flag);
        jTextField_CadastroUsuario_Email.setEnabled(flag);
        jComboBox_CadastroUsuario_Cargo.setEnabled(flag);
        // Se o cargo selecionado for OPERADOR, permite editar o combo de ADM
        String cargo = jComboBox_CadastroUsuario_Cargo.getSelectedItem().toString();
        jComboBox_CadastroUsuario_Adm.setEnabled(flag && cargo.equalsIgnoreCase("OPERADOR"));
    }

// Método que converte os campos da tela em um objeto Funcionario
// Aqui é feita a criação de um Operador ou Administrador de acordo com o cargo selecionado
    public Funcionario camposParaObjeto() {
        String nome = jTextField_CadastroUsuario_Nome.getText();
        String cpf = jTextField_CadastroUsuario_CPF.getText();
        String matricula = jTextField_CadastroUsuario_Matricula.getText();
        String senha = jTextField_CadastroUsuario_Senha.getText();
        String email = jTextField_CadastroUsuario_Email.getText();
        String cargo = jComboBox_CadastroUsuario_Cargo.getSelectedItem().toString();

        if (cargo.equalsIgnoreCase("OPERADOR")) {
            Operador operador = new Operador(nome, cpf, matricula, senha, email);
            Object item = jComboBox_CadastroUsuario_Adm.getSelectedItem();
            if (item != null && item instanceof Administrador) {
                operador.setAdministrador((Administrador) item);
            } else {
                operador.setAdministrador(null);
            }
            return operador;
        } else if (cargo.equalsIgnoreCase("ADMINISTRADOR")) {
            return new Administrador(nome, cpf, matricula, senha, email);
        } else {
            throw new RuntimeException("Cargo inválido: " + cargo);
        }
    }

    // Transfere os dados do objeto para os campos da tela
    public void objetoParaCampos(Funcionario funcionario) {
        jTextField_CadastroUsuario_Nome.setText(funcionario.getNome());
        jTextField_CadastroUsuario_CPF.setText(funcionario.getCpf());
        jTextField_CadastroUsuario_Matricula.setText(funcionario.getMatricula());
        jTextField_CadastroUsuario_Senha.setText(funcionario.getSenha());
        jTextField_CadastroUsuario_Email.setText(funcionario.getEmail());
        jComboBox_CadastroUsuario_Cargo.setSelectedItem(funcionario.getCargo());

        // Se for Operador, seleciona o Administrador associado (se houver)
        if (funcionario instanceof Operador) {
            Operador op = (Operador) funcionario;
            jComboBox_CadastroUsuario_Adm.setEnabled(true);
            jComboBox_CadastroUsuario_Adm.setSelectedItem(op.getAdministrador());
        } else {
            jComboBox_CadastroUsuario_Adm.setEnabled(false);
            jComboBox_CadastroUsuario_Adm.setSelectedItem(null);
        }
    }

    // Atualiza o combobox de administradores conforme o cargo selecionado
    private void atualizarComboAdm() {
        String cargo = jComboBox_CadastroUsuario_Cargo.getSelectedItem().toString();
        if (cargo.equalsIgnoreCase("OPERADOR")) {
            jComboBox_CadastroUsuario_Adm.setEnabled(true);
            // Obtém a lista de funcionários e filtra os administradores
            List<Funcionario> funcionarios = gerente.getFuncionarios();
            List<Administrador> listaAdmins = new ArrayList<>();
            for (Funcionario f : funcionarios) {
                if (f instanceof Administrador) {
                    listaAdmins.add((Administrador) f);
                }
            }
            // Adiciona uma opção "Nenhum" no início para representar null
            listaAdmins.add(0, null);
            jComboBox_CadastroUsuario_Adm.setModel(new DefaultComboBoxModel(listaAdmins.toArray()));
        } else {
            jComboBox_CadastroUsuario_Adm.setEnabled(false);
            jComboBox_CadastroUsuario_Adm.setSelectedItem(null);
        }
    }


    private void jButton_CadastroUsuario_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_NovoActionPerformed
        this.limparCampos();
        this.habilitarCampos(true);
        this.editando = false;
    }//GEN-LAST:event_jButton_CadastroUsuario_NovoActionPerformed

    private void jButton_CadastroUsuario_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_EditarActionPerformed
        this.cadastroSelecionado = JOptionPane.showInputDialog("Informe a matricula do cadastro selecionado:", "");
        Funcionario cadastroEditando = this.gerente.buscarCadastro(cadastroSelecionado);
        if (cadastroEditando != null) {
            this.editando = true;
            this.limparCampos();
            this.habilitarCampos(true);
            objetoParaCampos(cadastroEditando);
        } else {
            System.out.println("Cadastro inexistente");
            JOptionPane.showMessageDialog(this, "A matricula informada não foi encontrada no sistema.", "Cadastro Inexistente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_CadastroUsuario_EditarActionPerformed

    private void jButton_CadastroUsuario_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_CancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_jButton_CadastroUsuario_CancelarActionPerformed

    private void jButton_CadastroUsuario_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_ExcluirActionPerformed
        this.cadastroSelecionado = JOptionPane.showInputDialog("Informe a matricula do cadastro a ser excluído:", "");
        Funcionario cadastro = this.gerente.buscarCadastro(cadastroSelecionado);
        if (cadastro == null) {
            JOptionPane.showMessageDialog(this, "O cadastro informado não foi encontrado no sistema.", "Cadastro Inexistente", HEIGHT);
        } else {
            this.gerente.removerCadastro(cadastroSelecionado);
            JOptionPane.showMessageDialog(this, "Cadastro excluído com sucesso.", "Cadastro Excluído", HEIGHT);
        }
    }//GEN-LAST:event_jButton_CadastroUsuario_ExcluirActionPerformed

    private void jButton_CadastroUsuario_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_SalvarActionPerformed
        try {
            Funcionario novoCadastro = this.camposParaObjeto();
            if (this.editando) {
                this.gerente.atualizarCadastro(this.cadastroSelecionado, novoCadastro);
            } else {
                this.gerente.adicionarCadastro(novoCadastro);
            }
            this.limparCampos();
            this.habilitarCampos(false);
            this.editando = false;
        } catch (CadastroException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton_CadastroUsuario_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CadastroUsuario_Cancelar;
    private javax.swing.JButton jButton_CadastroUsuario_Editar;
    private javax.swing.JButton jButton_CadastroUsuario_Excluir;
    private javax.swing.JButton jButton_CadastroUsuario_Novo;
    private javax.swing.JButton jButton_CadastroUsuario_Salvar;
    private javax.swing.JComboBox<String> jComboBox_CadastroUsuario_Adm;
    private javax.swing.JComboBox<String> jComboBox_CadastroUsuario_Cargo;
    private javax.swing.JLabel jLabel_CadastroUsuario_Adm;
    private javax.swing.JLabel jLabel_CadastroUsuario_CPF;
    private javax.swing.JLabel jLabel_CadastroUsuario_Cargo;
    private javax.swing.JLabel jLabel_CadastroUsuario_Email;
    private javax.swing.JLabel jLabel_CadastroUsuario_Matrícula;
    private javax.swing.JLabel jLabel_CadastroUsuario_Nome;
    private javax.swing.JLabel jLabel_CadastroUsuario_Senha;
    private javax.swing.JLabel jLabel_CadastroUsuario_Título;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField_CadastroUsuario_CPF;
    private javax.swing.JTextField jTextField_CadastroUsuario_Email;
    private javax.swing.JTextField jTextField_CadastroUsuario_Matricula;
    private javax.swing.JTextField jTextField_CadastroUsuario_Nome;
    private javax.swing.JTextField jTextField_CadastroUsuario_Senha;
    // End of variables declaration//GEN-END:variables
}
