/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.GerenciadorCadastros;
import javax.swing.JOptionPane;
import model.Cadastro;
import model.exception.CadastroException;

/**
 *
 * @author rafae
 */
public class DlgCadastroUsuario extends javax.swing.JDialog {

    private String cadastroSelecionado;
    private boolean editando;
    private GerenciadorCadastros gerente;

    public DlgCadastroUsuario(boolean modal) {
        this.editando = false;
        this.cadastroSelecionado = "";
        this.gerente = new GerenciadorCadastros();
        initComponents();
        setTitle("Cadastro");
        this.habilitarCampos(false);
        this.limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_CadastroUsuario_Novo = new javax.swing.JButton();
        jButton_CadastroUsuario_Editar = new javax.swing.JButton();
        jButton_CadastroUsuario_Cancelar = new javax.swing.JButton();
        jButton_CadastroUsuario_Excluir = new javax.swing.JButton();
        jButton_CadastroUsuario_Salvar = new javax.swing.JButton();
        jLabel_CadastroUsuario_Título = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_CadastroUsuario_Nome = new javax.swing.JLabel();
        jTextField_CadastroUsuario_Nome = new javax.swing.JTextField();
        jLabel_CadastroUsuario_CPF = new javax.swing.JLabel();
        jLabel_CadastroUsuario_Senha = new javax.swing.JLabel();
        jTextField_CadastroUsuario_CPF = new javax.swing.JTextField();
        jTextField_CadastroUsuario_Senha = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextField_CadastroUsuario_Matricula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(583, 145));
        setMinimumSize(new java.awt.Dimension(583, 145));
        setModal(true);
        setResizable(false);

        jButton_CadastroUsuario_Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-novo.png"))); // NOI18N
        jButton_CadastroUsuario_Novo.setText("Novo");
        jButton_CadastroUsuario_Novo.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Novo.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Novo.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_NovoActionPerformed(evt);
            }
        });

        jButton_CadastroUsuario_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-editar-20.png"))); // NOI18N
        jButton_CadastroUsuario_Editar.setText("Editar");
        jButton_CadastroUsuario_Editar.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Editar.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Editar.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_EditarActionPerformed(evt);
            }
        });

        jButton_CadastroUsuario_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancelar-20 (1).png"))); // NOI18N
        jButton_CadastroUsuario_Cancelar.setText("Cancelar");
        jButton_CadastroUsuario_Cancelar.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Cancelar.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Cancelar.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_CancelarActionPerformed(evt);
            }
        });

        jButton_CadastroUsuario_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-excluir.png"))); // NOI18N
        jButton_CadastroUsuario_Excluir.setText("Excluir");
        jButton_CadastroUsuario_Excluir.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Excluir.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Excluir.setPreferredSize(new java.awt.Dimension(100, 27));
        jButton_CadastroUsuario_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_ExcluirActionPerformed(evt);
            }
        });

        jButton_CadastroUsuario_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-salvar.png"))); // NOI18N
        jButton_CadastroUsuario_Salvar.setText("Salvar");
        jButton_CadastroUsuario_Salvar.setMaximumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Salvar.setMinimumSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Salvar.setPreferredSize(new java.awt.Dimension(110, 27));
        jButton_CadastroUsuario_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_SalvarActionPerformed(evt);
            }
        });

        jLabel_CadastroUsuario_Título.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_CadastroUsuario_Título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CadastroUsuario_Título.setText("Cadastro de Usuários");

        jLabel_CadastroUsuario_Nome.setText("Nome:");

        jTextField_CadastroUsuario_Nome.setMaximumSize(new java.awt.Dimension(210, 22));
        jTextField_CadastroUsuario_Nome.setMinimumSize(new java.awt.Dimension(210, 22));
        jTextField_CadastroUsuario_Nome.setPreferredSize(new java.awt.Dimension(210, 22));

        jLabel_CadastroUsuario_CPF.setText("CPF:");

        jLabel_CadastroUsuario_Senha.setText("Senha");

        jTextField_CadastroUsuario_CPF.setMaximumSize(new java.awt.Dimension(190, 22));
        jTextField_CadastroUsuario_CPF.setMinimumSize(new java.awt.Dimension(190, 22));
        jTextField_CadastroUsuario_CPF.setPreferredSize(new java.awt.Dimension(190, 22));

        jTextField_CadastroUsuario_Senha.setMaximumSize(new java.awt.Dimension(190, 22));
        jTextField_CadastroUsuario_Senha.setMinimumSize(new java.awt.Dimension(190, 22));
        jTextField_CadastroUsuario_Senha.setPreferredSize(new java.awt.Dimension(190, 22));

        jLabel1.setText("Matricula:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CadastroUsuario_Título, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_CadastroUsuario_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton_CadastroUsuario_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton_CadastroUsuario_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton_CadastroUsuario_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_CadastroUsuario_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_CadastroUsuario_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CadastroUsuario_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel_CadastroUsuario_CPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CadastroUsuario_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CadastroUsuario_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel_CadastroUsuario_Senha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CadastroUsuario_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_CadastroUsuario_Título, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CadastroUsuario_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroUsuario_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroUsuario_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroUsuario_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroUsuario_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CadastroUsuario_Nome)
                    .addComponent(jTextField_CadastroUsuario_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CadastroUsuario_CPF)
                    .addComponent(jTextField_CadastroUsuario_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CadastroUsuario_Senha)
                    .addComponent(jTextField_CadastroUsuario_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_CadastroUsuario_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void limparCampos() {
        this.jTextField_CadastroUsuario_Nome.setText("");
        this.jTextField_CadastroUsuario_Senha.setText("");
        this.jTextField_CadastroUsuario_Matricula.setText("");
        this.jTextField_CadastroUsuario_CPF.setText("");
    }

    public void habilitarCampos(boolean flag) {
        this.jTextField_CadastroUsuario_Nome.setEnabled(flag);
        this.jTextField_CadastroUsuario_Senha.setEnabled(flag);
        this.jTextField_CadastroUsuario_Matricula.setEnabled(flag);
        this.jTextField_CadastroUsuario_CPF.setEnabled(flag);
    }

    public Cadastro camposParaObjeto() {
        Cadastro cadastro = new Cadastro();
        cadastro.setNome(jTextField_CadastroUsuario_Nome.getText());
        cadastro.setCpf(jTextField_CadastroUsuario_CPF.getText());
        cadastro.setMatricula(jTextField_CadastroUsuario_Matricula.getText());
        cadastro.setSenha(jTextField_CadastroUsuario_Senha.getText());
        return cadastro;
    }

    public void objetoParaCampos(Cadastro cadastro) {
        jTextField_CadastroUsuario_Nome.setText(cadastro.getNome());
        jTextField_CadastroUsuario_CPF.setText(cadastro.getCpf());
        jTextField_CadastroUsuario_Matricula.setText(cadastro.getMatricula());
        jTextField_CadastroUsuario_Senha.setText(cadastro.getSenha());
    }

    private void jButton_CadastroUsuario_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_NovoActionPerformed
        this.limparCampos();
        this.habilitarCampos(true);
        this.editando = false;
    }//GEN-LAST:event_jButton_CadastroUsuario_NovoActionPerformed

    private void jButton_CadastroUsuario_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_EditarActionPerformed
        this.cadastroSelecionado = JOptionPane.showInputDialog("Informe a matricula do cadastro selecionado:", "");
        Cadastro cadastroEditando = this.gerente.buscarCadastro(cadastroSelecionado);
        if (cadastroEditando != null) {
            this.editando = true;
            this.limparCampos();
            this.habilitarCampos(true);
            objetoParaCampos(cadastroEditando);

        } else {
            System.out.println("cadastro inexistente");
            JOptionPane.showMessageDialog(this, "A matricula informada não foi encontrada no sistema.", "Cadastro Inexistente", HEIGHT);
        }
    }//GEN-LAST:event_jButton_CadastroUsuario_EditarActionPerformed

    private void jButton_CadastroUsuario_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_CancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_jButton_CadastroUsuario_CancelarActionPerformed

    private void jButton_CadastroUsuario_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_ExcluirActionPerformed
        this.cadastroSelecionado = JOptionPane.showInputDialog("Informe a matricula do cadastro a ser excluído:", "");
        Cadastro cadastro = this.gerente.buscarCadastro(cadastroSelecionado);
        if (cadastro == null) {
            JOptionPane.showMessageDialog(this, "O cadastro informado não foi encontrado no sistema.", "Cadastro Inexistente", HEIGHT);
        } else {
            this.gerente.removerCadastro(cadastroSelecionado);
            JOptionPane.showMessageDialog(this, "Cadastro excluído com sucesso.", "Cadastro Excluído", HEIGHT);
        }
    }//GEN-LAST:event_jButton_CadastroUsuario_ExcluirActionPerformed

    private void jButton_CadastroUsuario_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_SalvarActionPerformed
        try {
            Cadastro novoCadastro = this.camposParaObjeto();
            if (this.editando) {
                this.gerente.atualizarCadastro(this.cadastroSelecionado, novoCadastro);
            } else {
                this.gerente.adicionarCadastro(novoCadastro);
            }
            this.limparCampos();
            this.habilitarCampos(false);
            this.editando = false;
        } catch (CadastroException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton_CadastroUsuario_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CadastroUsuario_Cancelar;
    private javax.swing.JButton jButton_CadastroUsuario_Editar;
    private javax.swing.JButton jButton_CadastroUsuario_Excluir;
    private javax.swing.JButton jButton_CadastroUsuario_Novo;
    private javax.swing.JButton jButton_CadastroUsuario_Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_CadastroUsuario_CPF;
    private javax.swing.JLabel jLabel_CadastroUsuario_Nome;
    private javax.swing.JLabel jLabel_CadastroUsuario_Senha;
    private javax.swing.JLabel jLabel_CadastroUsuario_Título;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField_CadastroUsuario_CPF;
    private javax.swing.JTextField jTextField_CadastroUsuario_Matricula;
    private javax.swing.JTextField jTextField_CadastroUsuario_Nome;
    private javax.swing.JTextField jTextField_CadastroUsuario_Senha;
    // End of variables declaration//GEN-END:variables
}
